name: ms-gen
channels:
- pytorch
- dglteam
- conda-forge
- pyg
- bioconda
dependencies:
- python=3.8.*
- cython
- matplotlib=3.4.*
- rdkit=2021.03.*
- conda-forge::python-graphviz=0.17
- conda-forge::pygraphviz=1.7
- pytorch-lightning=1.6.*
- pip=21.2.*
- ipykernel=6.0.*
- pytorch::pytorch=1.9.1=py3.8_cuda11.1_cudnn8.0.5_0
- cudatoolkit=11.1
- einops
- nb_conda_kernels=2.3.*
- seaborn=0.11.*
- ray-tune
- pytorch-scatter
- pytorch-sparse
- pyg
- dgl-cuda11.1=0.8.2
- MKL=2024.0.0
